version: '3.8'
services:
  taggare-client:
    container_name: taggare-client
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4000:4000'
    environment:
      - CHOKIDAR_USEPOLLING=true
  web:
    image: nginx:latest
    container_name: web
    restart: 'on-failure'
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
